version: 0.0
os: linux
files:
  - source: /app.js
    destination: /var/www/app/
  - source: /package.json
    destination: /var/www/app/    
hooks:
  AfterInstall:
    - location: scripts/build_proj
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root